version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:12.13
  working_directory: ~/ui-driver-xelon

release: &release
  docker:
    - image: cibuilds/github:0.13
  working_directory: ~/ui-driver-xelon

references:
  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/ui-driver-xelon
  persist_workspace: &persist_workspace
    persist_to_workspace:
      root: ~/ui-driver-xelon
      paths:
        - "*"
  save_npm_cache: &save_npm_cache
    save_cache:
      key: node_modules-{{ checksum "package.json" }}
      paths:
        - "node_modules"
  restore_npm_cache: &restore_npm_cache
    restore_cache:
      keys:
        - node_modules-{{ checksum "package.json" }}
        - node_modules-


jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - *restore_npm_cache
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Build
          command: |
            npm run build
      - *save_npm_cache
      - *persist_workspace

  github-release:
    <<: *release
    steps:
      - *attach_workspace
      - run:
          name: Publish release on GitHub
          command: |
            ghr --token ${GITHUB_TOKEN} --username ${CIRCLE_PROJECT_USERNAME} --repository ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${CIRCLE_TAG} ./dist/

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - github-release:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
